# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: companies.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x63ompanies.proto\x12\x17licenta.drona.companies\"L\n\x07\x43ompany\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x12\n\nowner_name\x18\x03 \x01(\t\x12\x13\n\x0bproduct_ids\x18\x04 \x03(\t\"8\n\x14\x43reateCompanyRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x12\n\nowner_name\x18\x02 \x01(\t\"I\n\x15\x43reateCompanyResponse\x12\x30\n\x06result\x18\x01 \x01(\x0b\x32 .licenta.drona.companies.Company\"G\n\x13GetCompaniesRequest\x12\x30\n\x06\x66ilter\x18\x01 \x01(\x0b\x32 .licenta.drona.companies.Company\"I\n\x14GetCompaniesResponse\x12\x31\n\x07results\x18\x01 \x03(\x0b\x32 .licenta.drona.companies.Company\"e\n\x14UpdateCompanyRequest\x12\x35\n\x0bnew_company\x18\x01 \x01(\x0b\x32 .licenta.drona.companies.Company\x12\x16\n\x0eold_company_id\x18\x02 \x01(\t\"I\n\x15UpdateCompanyResponse\x12\x30\n\x06result\x18\x01 \x01(\x0b\x32 .licenta.drona.companies.Company\"\"\n\x14\x44\x65leteCompanyRequest\x12\n\n\x02id\x18\x01 \x01(\t\"I\n\x15\x44\x65leteCompanyResponse\x12\x30\n\x06result\x18\x01 \x01(\x0b\x32 .licenta.drona.companies.Company2\xcf\x03\n\x10\x43ompaniesService\x12n\n\rCreateCompany\x12-.licenta.drona.companies.CreateCompanyRequest\x1a..licenta.drona.companies.CreateCompanyResponse\x12k\n\x0cGetCompanies\x12,.licenta.drona.companies.GetCompaniesRequest\x1a-.licenta.drona.companies.GetCompaniesResponse\x12n\n\rUpdateCompany\x12-.licenta.drona.companies.UpdateCompanyRequest\x1a..licenta.drona.companies.UpdateCompanyResponse\x12n\n\rDeleteCompany\x12-.licenta.drona.companies.DeleteCompanyRequest\x1a..licenta.drona.companies.DeleteCompanyResponseb\x06proto3')



_COMPANY = DESCRIPTOR.message_types_by_name['Company']
_CREATECOMPANYREQUEST = DESCRIPTOR.message_types_by_name['CreateCompanyRequest']
_CREATECOMPANYRESPONSE = DESCRIPTOR.message_types_by_name['CreateCompanyResponse']
_GETCOMPANIESREQUEST = DESCRIPTOR.message_types_by_name['GetCompaniesRequest']
_GETCOMPANIESRESPONSE = DESCRIPTOR.message_types_by_name['GetCompaniesResponse']
_UPDATECOMPANYREQUEST = DESCRIPTOR.message_types_by_name['UpdateCompanyRequest']
_UPDATECOMPANYRESPONSE = DESCRIPTOR.message_types_by_name['UpdateCompanyResponse']
_DELETECOMPANYREQUEST = DESCRIPTOR.message_types_by_name['DeleteCompanyRequest']
_DELETECOMPANYRESPONSE = DESCRIPTOR.message_types_by_name['DeleteCompanyResponse']
Company = _reflection.GeneratedProtocolMessageType('Company', (_message.Message,), {
  'DESCRIPTOR' : _COMPANY,
  '__module__' : 'companies_pb2'
  # @@protoc_insertion_point(class_scope:licenta.drona.companies.Company)
  })
_sym_db.RegisterMessage(Company)

CreateCompanyRequest = _reflection.GeneratedProtocolMessageType('CreateCompanyRequest', (_message.Message,), {
  'DESCRIPTOR' : _CREATECOMPANYREQUEST,
  '__module__' : 'companies_pb2'
  # @@protoc_insertion_point(class_scope:licenta.drona.companies.CreateCompanyRequest)
  })
_sym_db.RegisterMessage(CreateCompanyRequest)

CreateCompanyResponse = _reflection.GeneratedProtocolMessageType('CreateCompanyResponse', (_message.Message,), {
  'DESCRIPTOR' : _CREATECOMPANYRESPONSE,
  '__module__' : 'companies_pb2'
  # @@protoc_insertion_point(class_scope:licenta.drona.companies.CreateCompanyResponse)
  })
_sym_db.RegisterMessage(CreateCompanyResponse)

GetCompaniesRequest = _reflection.GeneratedProtocolMessageType('GetCompaniesRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETCOMPANIESREQUEST,
  '__module__' : 'companies_pb2'
  # @@protoc_insertion_point(class_scope:licenta.drona.companies.GetCompaniesRequest)
  })
_sym_db.RegisterMessage(GetCompaniesRequest)

GetCompaniesResponse = _reflection.GeneratedProtocolMessageType('GetCompaniesResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETCOMPANIESRESPONSE,
  '__module__' : 'companies_pb2'
  # @@protoc_insertion_point(class_scope:licenta.drona.companies.GetCompaniesResponse)
  })
_sym_db.RegisterMessage(GetCompaniesResponse)

UpdateCompanyRequest = _reflection.GeneratedProtocolMessageType('UpdateCompanyRequest', (_message.Message,), {
  'DESCRIPTOR' : _UPDATECOMPANYREQUEST,
  '__module__' : 'companies_pb2'
  # @@protoc_insertion_point(class_scope:licenta.drona.companies.UpdateCompanyRequest)
  })
_sym_db.RegisterMessage(UpdateCompanyRequest)

UpdateCompanyResponse = _reflection.GeneratedProtocolMessageType('UpdateCompanyResponse', (_message.Message,), {
  'DESCRIPTOR' : _UPDATECOMPANYRESPONSE,
  '__module__' : 'companies_pb2'
  # @@protoc_insertion_point(class_scope:licenta.drona.companies.UpdateCompanyResponse)
  })
_sym_db.RegisterMessage(UpdateCompanyResponse)

DeleteCompanyRequest = _reflection.GeneratedProtocolMessageType('DeleteCompanyRequest', (_message.Message,), {
  'DESCRIPTOR' : _DELETECOMPANYREQUEST,
  '__module__' : 'companies_pb2'
  # @@protoc_insertion_point(class_scope:licenta.drona.companies.DeleteCompanyRequest)
  })
_sym_db.RegisterMessage(DeleteCompanyRequest)

DeleteCompanyResponse = _reflection.GeneratedProtocolMessageType('DeleteCompanyResponse', (_message.Message,), {
  'DESCRIPTOR' : _DELETECOMPANYRESPONSE,
  '__module__' : 'companies_pb2'
  # @@protoc_insertion_point(class_scope:licenta.drona.companies.DeleteCompanyResponse)
  })
_sym_db.RegisterMessage(DeleteCompanyResponse)

_COMPANIESSERVICE = DESCRIPTOR.services_by_name['CompaniesService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _COMPANY._serialized_start=44
  _COMPANY._serialized_end=120
  _CREATECOMPANYREQUEST._serialized_start=122
  _CREATECOMPANYREQUEST._serialized_end=178
  _CREATECOMPANYRESPONSE._serialized_start=180
  _CREATECOMPANYRESPONSE._serialized_end=253
  _GETCOMPANIESREQUEST._serialized_start=255
  _GETCOMPANIESREQUEST._serialized_end=326
  _GETCOMPANIESRESPONSE._serialized_start=328
  _GETCOMPANIESRESPONSE._serialized_end=401
  _UPDATECOMPANYREQUEST._serialized_start=403
  _UPDATECOMPANYREQUEST._serialized_end=504
  _UPDATECOMPANYRESPONSE._serialized_start=506
  _UPDATECOMPANYRESPONSE._serialized_end=579
  _DELETECOMPANYREQUEST._serialized_start=581
  _DELETECOMPANYREQUEST._serialized_end=615
  _DELETECOMPANYRESPONSE._serialized_start=617
  _DELETECOMPANYRESPONSE._serialized_end=690
  _COMPANIESSERVICE._serialized_start=693
  _COMPANIESSERVICE._serialized_end=1156
# @@protoc_insertion_point(module_scope)
