# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: drone_manager.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x64rone_manager.proto\x12\x11\x61\x63s.drone_manager\x1a\x1bgoogle/protobuf/empty.proto\"1\n\x0eSetGoalRequest\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\t\n\x01z\x18\x03 \x01(\x02\"4\n\x0fSetGoalResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x10\n\x08order_id\x18\x02 \x01(\t\"$\n\x11LandDroneResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"&\n\x13ReturnDroneResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\xfa\x01\n\x0c\x44roneManager\x12P\n\x07SetGoal\x12!.acs.drone_manager.SetGoalRequest\x1a\".acs.drone_manager.SetGoalResponse\x12I\n\tLandDrone\x12\x16.google.protobuf.Empty\x1a$.acs.drone_manager.LandDroneResponse\x12M\n\x0bReturnDrone\x12\x16.google.protobuf.Empty\x1a&.acs.drone_manager.ReturnDroneResponseb\x06proto3')



_SETGOALREQUEST = DESCRIPTOR.message_types_by_name['SetGoalRequest']
_SETGOALRESPONSE = DESCRIPTOR.message_types_by_name['SetGoalResponse']
_LANDDRONERESPONSE = DESCRIPTOR.message_types_by_name['LandDroneResponse']
_RETURNDRONERESPONSE = DESCRIPTOR.message_types_by_name['ReturnDroneResponse']
SetGoalRequest = _reflection.GeneratedProtocolMessageType('SetGoalRequest', (_message.Message,), {
  'DESCRIPTOR' : _SETGOALREQUEST,
  '__module__' : 'drone_manager_pb2'
  # @@protoc_insertion_point(class_scope:acs.drone_manager.SetGoalRequest)
  })
_sym_db.RegisterMessage(SetGoalRequest)

SetGoalResponse = _reflection.GeneratedProtocolMessageType('SetGoalResponse', (_message.Message,), {
  'DESCRIPTOR' : _SETGOALRESPONSE,
  '__module__' : 'drone_manager_pb2'
  # @@protoc_insertion_point(class_scope:acs.drone_manager.SetGoalResponse)
  })
_sym_db.RegisterMessage(SetGoalResponse)

LandDroneResponse = _reflection.GeneratedProtocolMessageType('LandDroneResponse', (_message.Message,), {
  'DESCRIPTOR' : _LANDDRONERESPONSE,
  '__module__' : 'drone_manager_pb2'
  # @@protoc_insertion_point(class_scope:acs.drone_manager.LandDroneResponse)
  })
_sym_db.RegisterMessage(LandDroneResponse)

ReturnDroneResponse = _reflection.GeneratedProtocolMessageType('ReturnDroneResponse', (_message.Message,), {
  'DESCRIPTOR' : _RETURNDRONERESPONSE,
  '__module__' : 'drone_manager_pb2'
  # @@protoc_insertion_point(class_scope:acs.drone_manager.ReturnDroneResponse)
  })
_sym_db.RegisterMessage(ReturnDroneResponse)

_DRONEMANAGER = DESCRIPTOR.services_by_name['DroneManager']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SETGOALREQUEST._serialized_start=71
  _SETGOALREQUEST._serialized_end=120
  _SETGOALRESPONSE._serialized_start=122
  _SETGOALRESPONSE._serialized_end=174
  _LANDDRONERESPONSE._serialized_start=176
  _LANDDRONERESPONSE._serialized_end=212
  _RETURNDRONERESPONSE._serialized_start=214
  _RETURNDRONERESPONSE._serialized_end=252
  _DRONEMANAGER._serialized_start=255
  _DRONEMANAGER._serialized_end=505
# @@protoc_insertion_point(module_scope)
