# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: order_tracking.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14order_tracking.proto\x12\x12\x61\x63s.order_tracking\x1a\x1bgoogle/protobuf/empty.proto\"#\n\x0b\x44\x65stination\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\"\x83\x01\n\x05Order\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12*\n\x06status\x18\x03 \x01(\x0e\x32\x1a.acs.order_tracking.Status\x12\x34\n\x0b\x64\x65stination\x18\x04 \x01(\x0b\x32\x1f.acs.order_tracking.Destination\"X\n\x12\x43reateOrderRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x34\n\x0b\x64\x65stination\x18\x02 \x01(\x0b\x32\x1f.acs.order_tracking.Destination\"?\n\x13\x43reateOrderResponse\x12(\n\x05order\x18\x01 \x01(\x0b\x32\x19.acs.order_tracking.Order\"\x1d\n\x0fGetOrderRequest\x12\n\n\x02id\x18\x01 \x01(\t\"<\n\x10GetOrderResponse\x12(\n\x05order\x18\x01 \x01(\x0b\x32\x19.acs.order_tracking.Order\"L\n\x12UpdateOrderRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12*\n\x06status\x18\x02 \x01(\x0e\x32\x1a.acs.order_tracking.Status\"?\n\x13UpdateOrderResponse\x12(\n\x05order\x18\x01 \x01(\x0b\x32\x19.acs.order_tracking.Order\" \n\x12\x44\x65leteOrderRequest\x12\n\n\x02id\x18\x01 \x01(\t\"?\n\x13\x44\x65leteOrderResponse\x12(\n\x05order\x18\x01 \x01(\x0b\x32\x19.acs.order_tracking.Order*Q\n\x06Status\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0b\n\x07\x43REATED\x10\x01\x12\x0f\n\x0bIN_PROGRESS\x10\x02\x12\r\n\tCOMPLETED\x10\x03\x12\r\n\tCANCELLED\x10\x04\x32\x8d\x03\n\x14OrderTrackingService\x12^\n\x0b\x43reateOrder\x12&.acs.order_tracking.CreateOrderRequest\x1a\'.acs.order_tracking.CreateOrderResponse\x12U\n\x08GetOrder\x12#.acs.order_tracking.GetOrderRequest\x1a$.acs.order_tracking.GetOrderResponse\x12^\n\x0bUpdateOrder\x12&.acs.order_tracking.UpdateOrderRequest\x1a\'.acs.order_tracking.UpdateOrderResponse\x12^\n\x0b\x44\x65leteOrder\x12&.acs.order_tracking.DeleteOrderRequest\x1a\'.acs.order_tracking.DeleteOrderResponseb\x06proto3')

_STATUS = DESCRIPTOR.enum_types_by_name['Status']
Status = enum_type_wrapper.EnumTypeWrapper(_STATUS)
UNKNOWN = 0
CREATED = 1
IN_PROGRESS = 2
COMPLETED = 3
CANCELLED = 4


_DESTINATION = DESCRIPTOR.message_types_by_name['Destination']
_ORDER = DESCRIPTOR.message_types_by_name['Order']
_CREATEORDERREQUEST = DESCRIPTOR.message_types_by_name['CreateOrderRequest']
_CREATEORDERRESPONSE = DESCRIPTOR.message_types_by_name['CreateOrderResponse']
_GETORDERREQUEST = DESCRIPTOR.message_types_by_name['GetOrderRequest']
_GETORDERRESPONSE = DESCRIPTOR.message_types_by_name['GetOrderResponse']
_UPDATEORDERREQUEST = DESCRIPTOR.message_types_by_name['UpdateOrderRequest']
_UPDATEORDERRESPONSE = DESCRIPTOR.message_types_by_name['UpdateOrderResponse']
_DELETEORDERREQUEST = DESCRIPTOR.message_types_by_name['DeleteOrderRequest']
_DELETEORDERRESPONSE = DESCRIPTOR.message_types_by_name['DeleteOrderResponse']
Destination = _reflection.GeneratedProtocolMessageType('Destination', (_message.Message,), {
  'DESCRIPTOR' : _DESTINATION,
  '__module__' : 'order_tracking_pb2'
  # @@protoc_insertion_point(class_scope:acs.order_tracking.Destination)
  })
_sym_db.RegisterMessage(Destination)

Order = _reflection.GeneratedProtocolMessageType('Order', (_message.Message,), {
  'DESCRIPTOR' : _ORDER,
  '__module__' : 'order_tracking_pb2'
  # @@protoc_insertion_point(class_scope:acs.order_tracking.Order)
  })
_sym_db.RegisterMessage(Order)

CreateOrderRequest = _reflection.GeneratedProtocolMessageType('CreateOrderRequest', (_message.Message,), {
  'DESCRIPTOR' : _CREATEORDERREQUEST,
  '__module__' : 'order_tracking_pb2'
  # @@protoc_insertion_point(class_scope:acs.order_tracking.CreateOrderRequest)
  })
_sym_db.RegisterMessage(CreateOrderRequest)

CreateOrderResponse = _reflection.GeneratedProtocolMessageType('CreateOrderResponse', (_message.Message,), {
  'DESCRIPTOR' : _CREATEORDERRESPONSE,
  '__module__' : 'order_tracking_pb2'
  # @@protoc_insertion_point(class_scope:acs.order_tracking.CreateOrderResponse)
  })
_sym_db.RegisterMessage(CreateOrderResponse)

GetOrderRequest = _reflection.GeneratedProtocolMessageType('GetOrderRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETORDERREQUEST,
  '__module__' : 'order_tracking_pb2'
  # @@protoc_insertion_point(class_scope:acs.order_tracking.GetOrderRequest)
  })
_sym_db.RegisterMessage(GetOrderRequest)

GetOrderResponse = _reflection.GeneratedProtocolMessageType('GetOrderResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETORDERRESPONSE,
  '__module__' : 'order_tracking_pb2'
  # @@protoc_insertion_point(class_scope:acs.order_tracking.GetOrderResponse)
  })
_sym_db.RegisterMessage(GetOrderResponse)

UpdateOrderRequest = _reflection.GeneratedProtocolMessageType('UpdateOrderRequest', (_message.Message,), {
  'DESCRIPTOR' : _UPDATEORDERREQUEST,
  '__module__' : 'order_tracking_pb2'
  # @@protoc_insertion_point(class_scope:acs.order_tracking.UpdateOrderRequest)
  })
_sym_db.RegisterMessage(UpdateOrderRequest)

UpdateOrderResponse = _reflection.GeneratedProtocolMessageType('UpdateOrderResponse', (_message.Message,), {
  'DESCRIPTOR' : _UPDATEORDERRESPONSE,
  '__module__' : 'order_tracking_pb2'
  # @@protoc_insertion_point(class_scope:acs.order_tracking.UpdateOrderResponse)
  })
_sym_db.RegisterMessage(UpdateOrderResponse)

DeleteOrderRequest = _reflection.GeneratedProtocolMessageType('DeleteOrderRequest', (_message.Message,), {
  'DESCRIPTOR' : _DELETEORDERREQUEST,
  '__module__' : 'order_tracking_pb2'
  # @@protoc_insertion_point(class_scope:acs.order_tracking.DeleteOrderRequest)
  })
_sym_db.RegisterMessage(DeleteOrderRequest)

DeleteOrderResponse = _reflection.GeneratedProtocolMessageType('DeleteOrderResponse', (_message.Message,), {
  'DESCRIPTOR' : _DELETEORDERRESPONSE,
  '__module__' : 'order_tracking_pb2'
  # @@protoc_insertion_point(class_scope:acs.order_tracking.DeleteOrderResponse)
  })
_sym_db.RegisterMessage(DeleteOrderResponse)

_ORDERTRACKINGSERVICE = DESCRIPTOR.services_by_name['OrderTrackingService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _STATUS._serialized_start=734
  _STATUS._serialized_end=815
  _DESTINATION._serialized_start=73
  _DESTINATION._serialized_end=108
  _ORDER._serialized_start=111
  _ORDER._serialized_end=242
  _CREATEORDERREQUEST._serialized_start=244
  _CREATEORDERREQUEST._serialized_end=332
  _CREATEORDERRESPONSE._serialized_start=334
  _CREATEORDERRESPONSE._serialized_end=397
  _GETORDERREQUEST._serialized_start=399
  _GETORDERREQUEST._serialized_end=428
  _GETORDERRESPONSE._serialized_start=430
  _GETORDERRESPONSE._serialized_end=490
  _UPDATEORDERREQUEST._serialized_start=492
  _UPDATEORDERREQUEST._serialized_end=568
  _UPDATEORDERRESPONSE._serialized_start=570
  _UPDATEORDERRESPONSE._serialized_end=633
  _DELETEORDERREQUEST._serialized_start=635
  _DELETEORDERREQUEST._serialized_end=667
  _DELETEORDERRESPONSE._serialized_start=669
  _DELETEORDERRESPONSE._serialized_end=732
  _ORDERTRACKINGSERVICE._serialized_start=818
  _ORDERTRACKINGSERVICE._serialized_end=1215
# @@protoc_insertion_point(module_scope)
