# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: products.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eproducts.proto\x12\x16licenta.drona.products\"2\n\x07Product\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05price\x18\x03 \x01(\t\"3\n\x14\x43reateProductRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05price\x18\x02 \x01(\t\"I\n\x15\x43reateProductResponse\x12\x30\n\x07product\x18\x01 \x01(\x0b\x32\x1f.licenta.drona.products.Product\"M\n\x12GetProductsRequest\x12\x37\n\x0e\x66ilter_product\x18\x01 \x01(\x0b\x32\x1f.licenta.drona.products.Product\"H\n\x13GetProductsResponse\x12\x31\n\x08products\x18\x01 \x03(\x0b\x32\x1f.licenta.drona.products.Product\"d\n\x14UpdateProductRequest\x12\x34\n\x0bnew_product\x18\x01 \x01(\x0b\x32\x1f.licenta.drona.products.Product\x12\x16\n\x0eold_product_id\x18\x02 \x01(\t\"I\n\x15UpdateProductResponse\x12\x30\n\x07product\x18\x01 \x01(\x0b\x32\x1f.licenta.drona.products.Product\"\"\n\x14\x44\x65leteProductRequest\x12\n\n\x02id\x18\x01 \x01(\t\"#\n\x15\x44\x65leteProductResponse\x12\n\n\x02id\x18\x01 \x01(\t2\xc3\x03\n\x0fProductsService\x12l\n\rCreateProduct\x12,.licenta.drona.products.CreateProductRequest\x1a-.licenta.drona.products.CreateProductResponse\x12\x66\n\x0bGetProducts\x12*.licenta.drona.products.GetProductsRequest\x1a+.licenta.drona.products.GetProductsResponse\x12l\n\rUpdateProduct\x12,.licenta.drona.products.UpdateProductRequest\x1a-.licenta.drona.products.UpdateProductResponse\x12l\n\rDeleteProduct\x12,.licenta.drona.products.DeleteProductRequest\x1a-.licenta.drona.products.DeleteProductResponseb\x06proto3')



_PRODUCT = DESCRIPTOR.message_types_by_name['Product']
_CREATEPRODUCTREQUEST = DESCRIPTOR.message_types_by_name['CreateProductRequest']
_CREATEPRODUCTRESPONSE = DESCRIPTOR.message_types_by_name['CreateProductResponse']
_GETPRODUCTSREQUEST = DESCRIPTOR.message_types_by_name['GetProductsRequest']
_GETPRODUCTSRESPONSE = DESCRIPTOR.message_types_by_name['GetProductsResponse']
_UPDATEPRODUCTREQUEST = DESCRIPTOR.message_types_by_name['UpdateProductRequest']
_UPDATEPRODUCTRESPONSE = DESCRIPTOR.message_types_by_name['UpdateProductResponse']
_DELETEPRODUCTREQUEST = DESCRIPTOR.message_types_by_name['DeleteProductRequest']
_DELETEPRODUCTRESPONSE = DESCRIPTOR.message_types_by_name['DeleteProductResponse']
Product = _reflection.GeneratedProtocolMessageType('Product', (_message.Message,), {
  'DESCRIPTOR' : _PRODUCT,
  '__module__' : 'products_pb2'
  # @@protoc_insertion_point(class_scope:licenta.drona.products.Product)
  })
_sym_db.RegisterMessage(Product)

CreateProductRequest = _reflection.GeneratedProtocolMessageType('CreateProductRequest', (_message.Message,), {
  'DESCRIPTOR' : _CREATEPRODUCTREQUEST,
  '__module__' : 'products_pb2'
  # @@protoc_insertion_point(class_scope:licenta.drona.products.CreateProductRequest)
  })
_sym_db.RegisterMessage(CreateProductRequest)

CreateProductResponse = _reflection.GeneratedProtocolMessageType('CreateProductResponse', (_message.Message,), {
  'DESCRIPTOR' : _CREATEPRODUCTRESPONSE,
  '__module__' : 'products_pb2'
  # @@protoc_insertion_point(class_scope:licenta.drona.products.CreateProductResponse)
  })
_sym_db.RegisterMessage(CreateProductResponse)

GetProductsRequest = _reflection.GeneratedProtocolMessageType('GetProductsRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETPRODUCTSREQUEST,
  '__module__' : 'products_pb2'
  # @@protoc_insertion_point(class_scope:licenta.drona.products.GetProductsRequest)
  })
_sym_db.RegisterMessage(GetProductsRequest)

GetProductsResponse = _reflection.GeneratedProtocolMessageType('GetProductsResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETPRODUCTSRESPONSE,
  '__module__' : 'products_pb2'
  # @@protoc_insertion_point(class_scope:licenta.drona.products.GetProductsResponse)
  })
_sym_db.RegisterMessage(GetProductsResponse)

UpdateProductRequest = _reflection.GeneratedProtocolMessageType('UpdateProductRequest', (_message.Message,), {
  'DESCRIPTOR' : _UPDATEPRODUCTREQUEST,
  '__module__' : 'products_pb2'
  # @@protoc_insertion_point(class_scope:licenta.drona.products.UpdateProductRequest)
  })
_sym_db.RegisterMessage(UpdateProductRequest)

UpdateProductResponse = _reflection.GeneratedProtocolMessageType('UpdateProductResponse', (_message.Message,), {
  'DESCRIPTOR' : _UPDATEPRODUCTRESPONSE,
  '__module__' : 'products_pb2'
  # @@protoc_insertion_point(class_scope:licenta.drona.products.UpdateProductResponse)
  })
_sym_db.RegisterMessage(UpdateProductResponse)

DeleteProductRequest = _reflection.GeneratedProtocolMessageType('DeleteProductRequest', (_message.Message,), {
  'DESCRIPTOR' : _DELETEPRODUCTREQUEST,
  '__module__' : 'products_pb2'
  # @@protoc_insertion_point(class_scope:licenta.drona.products.DeleteProductRequest)
  })
_sym_db.RegisterMessage(DeleteProductRequest)

DeleteProductResponse = _reflection.GeneratedProtocolMessageType('DeleteProductResponse', (_message.Message,), {
  'DESCRIPTOR' : _DELETEPRODUCTRESPONSE,
  '__module__' : 'products_pb2'
  # @@protoc_insertion_point(class_scope:licenta.drona.products.DeleteProductResponse)
  })
_sym_db.RegisterMessage(DeleteProductResponse)

_PRODUCTSSERVICE = DESCRIPTOR.services_by_name['ProductsService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PRODUCT._serialized_start=42
  _PRODUCT._serialized_end=92
  _CREATEPRODUCTREQUEST._serialized_start=94
  _CREATEPRODUCTREQUEST._serialized_end=145
  _CREATEPRODUCTRESPONSE._serialized_start=147
  _CREATEPRODUCTRESPONSE._serialized_end=220
  _GETPRODUCTSREQUEST._serialized_start=222
  _GETPRODUCTSREQUEST._serialized_end=299
  _GETPRODUCTSRESPONSE._serialized_start=301
  _GETPRODUCTSRESPONSE._serialized_end=373
  _UPDATEPRODUCTREQUEST._serialized_start=375
  _UPDATEPRODUCTREQUEST._serialized_end=475
  _UPDATEPRODUCTRESPONSE._serialized_start=477
  _UPDATEPRODUCTRESPONSE._serialized_end=550
  _DELETEPRODUCTREQUEST._serialized_start=552
  _DELETEPRODUCTREQUEST._serialized_end=586
  _DELETEPRODUCTRESPONSE._serialized_start=588
  _DELETEPRODUCTRESPONSE._serialized_end=623
  _PRODUCTSSERVICE._serialized_start=626
  _PRODUCTSSERVICE._serialized_end=1077
# @@protoc_insertion_point(module_scope)
